allprojects {
    group = 'com.kingodogo'
    version = 'v1.0.0'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
    }
    
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}

