org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_id=cozyinteriors
mod_name=CozyInteriors
mod_license=All Rights Reserved
mod_version=v1.0.0
mod_group_id=com.kingodogo
mod_authors=Kingodogo
mod_description=Welcome to CozyInteriors - A mod focused on interior furniture such as chairs, sofas, tables, trash cans, postboxes, and more.

