pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = 'cozyinteriors'

include 'Versions:1.18.2'
include 'Versions:1.19'
include 'Versions:1.20.x'
include 'Versions:1.21.x'

project(':Versions:1.18.2').projectDir = file('Versions/1.18.2')
project(':Versions:1.19').projectDir = file('Versions/1.19')
project(':Versions:1.20.x').projectDir = file('Versions/1.20.x')
project(':Versions:1.21.x').projectDir = file('Versions/1.21.x')

