org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
forge_version=49.0.0
forge_version_range=[49,)
loader_version_range=[49,)
mapping_channel=official
mapping_version=1.21.11
mod_id=cozyinteriors
mod_name=CozyInteriors
mod_license=All Rights Reserved
mod_version=v1.0.0
mod_group_id=com.kingodogo
mod_authors=Kingodogo
mod_description=Welcome to CozyInteriors - A mod focused on interior furniture such as chairs, sofas, tables, trash cans, postboxes, and more.
